import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Viewport } from "next";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Choose weights as needed
  subsets: ["latin"], // Support Latin characters
  variable: "--font-poppins", // Custom CSS variable for the font
});

export const metadata: Metadata = {
  title: "Linguify",
  applicationName: "Linguify",
  manifest: "/manifest.json",

  // description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${poppins.variable} ${poppins.variable} antialiased`}
        >
          {/* <SignedOut>
            <SignInButton />
          </SignedOut> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
